### ISSUE TITLE
Your Stack Deadly Error

### ISSUE THREAD

**Issue by JeongTaehwan** [ZzukMa/ZzukMa#1]
Hi~ I'm Jeongtaehwan
There seems to be a huge error in your stack, so I leave an issue. Did you leave a project to call Spring substack? Or how much do you know about the spring? I'm curious. If you don't think it's your substack here, please revise it as soon as possible.

**Comment by minhyuuk** [comment]
Oh.. thank you for comment, but i'm learning spring for substack. Contact me if you're wondering my github
